// src/components/SlidePreview.tsx
/**
 * Live slide preview using shared Shiki singleton + magic-move.
 * Fixed: now uses per-slide atom for code to avoid re-render storm.
 * Fix: reads instant preview overrides from Zustand (previewProject / previewSlides / previewHighlights)
 * so fontSize / lineHeight / transitions update live during drag, not only on commit.
 */
import { useRef, useMemo } from "react";
import { useShikiDisplay } from "@/hooks/useShikiDisplay";
import {
  themeBackground,
  resolveProjectLanguage,
  type Project,
} from "@/types";
import { useEffectiveSettings } from "@/hooks/useEffectiveSettings";
import { usePreviewHighlightsMap } from "@/hooks/usePreviewSettings";
import { useSlideCode } from "@/hooks/useSlideCode";
import { useCurrentSlide } from "@/hooks/useCurrentSlide";
import { useUiStore } from "@/store/useUiStore";
import { HighlightLayer } from "./HighlightLayer";
import { MagicMoveBlock } from "./preview/MagicMoveBlock";
import { PreviewFallback } from "./preview/PreviewFallback";
import { PreviewStage } from "./preview/PreviewStage";

interface SlidePreviewProps {
  project: Project;
  isPresenting?: boolean;
  activeHighlightIndex?: number;
  onHighlightExitComplete?: () => void;
}

export function SlidePreview({
  project,
  isPresenting = false,
  activeHighlightIndex = -1,
  onHighlightExitComplete,
}: SlidePreviewProps) {
  const { activeSlide: slide } = useCurrentSlide(project);
  const code = useSlideCode(slide?.id, slide?.code ?? "");
  const containerRef = useRef<HTMLDivElement>(null);
  const codeContainerRef = useRef<HTMLDivElement>(null);

  // --- instant preview overrides ---
  const useEffective = useEffectiveSettings(project, slide);
  const previewHighlightsMap = usePreviewHighlightsMap();

  const language = resolveProjectLanguage(project);
  const previewTheme = useUiStore((state) => state.previewProject.theme);
  const theme = previewTheme ?? project.theme;

  const {
    shikiLoadFailed,
    displayHighlighter,
    displayTheme,
    displayLanguage,
  } = useShikiDisplay({ theme, language });

  if (!slide) {
    return (
      <div className="flex h-full w-full items-center justify-center text-muted-foreground">
        No slides
      </div>
    );
  }

  const s = project.settings;
  const settings = { ...s, fontSize: useEffective.fontSize, lineHeight: useEffective.lineHeight };

  const bg = themeBackground(displayTheme);
  const codeAlign = settings.codeAlign === "center" ? "center" : "left";
  const centerBlock = codeAlign === "center";

  const stagePad = isPresenting ? "p-16 md:p-24" : "p-8 md:p-12";

  const rawHighlights = slide.highlights ?? [];
  // Merge per-highlight preview overrides
  const highlights = useMemo(
    () =>
      rawHighlights.map((hl) => {
        const preview = previewHighlightsMap.get(hl.id);
        if (!preview) return hl;
        return { ...hl, ...preview };
      }),
    [rawHighlights, previewHighlightsMap],
  );

  const activeHighlight =
    activeHighlightIndex >= 0 && activeHighlightIndex < highlights.length
      ? highlights[activeHighlightIndex]
      : null;

  const previewFontSize = isPresenting
    ? settings.fontSize * 1.15
    : settings.fontSize;

  if (!displayHighlighter) {
    return (
      <PreviewFallback
        isMerustmarFail={language === "merustmar" && shikiLoadFailed}
        theme={displayTheme}
        code={code}
        fontSize={previewFontSize}
        lineHeight={settings.lineHeight}
        stagePad={stagePad}
        centerBlock={centerBlock}
        bg={bg}
        containerRef={containerRef}
      />
    );
  }

  return (
    <PreviewStage
      containerRef={containerRef}
      bg={bg}
      stagePad={stagePad}
      centerBlock={centerBlock}
    >
      <MagicMoveBlock
        codeContainerRef={codeContainerRef}
        centerBlock={centerBlock}
        lineHeight={settings.lineHeight}
        fontSize={previewFontSize}
        theme={displayTheme}
        language={displayLanguage}
        highlighter={displayHighlighter}
        code={code}
        transition={useEffective.transitionDuration}
        stagger={useEffective.stagger}
        showLineNumbers={settings.showLineNumbers}
      />
      <HighlightLayer
        containerRef={containerRef}
        codeContainerRef={codeContainerRef}
        code={code}
        highlight={activeHighlight}
        highlighter={displayHighlighter}
        theme={displayTheme}
        language={displayLanguage}
        fontSize={previewFontSize}
        lineHeight={settings.lineHeight}
        onExitComplete={onHighlightExitComplete}
      />
    </PreviewStage>
  );
}

// src/features/preview/SlidePreview.svelte
<script lang="ts">
  /**
   * Live slide preview using shared Shiki singleton + magic-move.
   * Reads instant preview overrides from the rune store
   * (previewProject / previewSlides / previewHighlights) so
   * fontSize / lineHeight / transitions update live during drag.
   */
  import { magicMoveShikiDisplay } from "$lib/shiki/shiki-display.svelte";
  import {
    themeBackground,
    resolveProjectLanguage,
    type Project,
  } from "$lib/types";
  import { createEffectiveSettings } from "@/features/settings/effective-settings.svelte";
  import {
    previewMergedHighlights,
    previewProjectSetting,
  } from "@/features/settings/preview-settings";
  import { effectiveSlideCode } from "$lib/stores/slide-code.svelte";
  import { createCurrentSlide } from "@/features/slides/current-slide.svelte";
  import HighlightLayer from "@/features/highlights/HighlightLayer.svelte";
  import MagicMoveBlock from "./MagicMoveBlock.svelte";
  import PreviewFallback from "./PreviewFallback.svelte";
  import PreviewStage from "./PreviewStage.svelte";

  let {
    project,
    isPresenting = false,
    activeHighlightIndex = -1,
    onHighlightExitComplete,
  }: {
    project: Project;
    isPresenting?: boolean;
    activeHighlightIndex?: number;
    onHighlightExitComplete?: () => void;
  } = $props();

  const currentSlide = createCurrentSlide(() => project);
  const slide = $derived(currentSlide.activeSlide);
  const code = $derived(effectiveSlideCode(slide));

  let containerEl = $state<HTMLDivElement | null>(null);
  let codeContainerEl = $state<HTMLDivElement | null>(null);

  // --- instant preview overrides ---
  const effective = createEffectiveSettings(() => project, () => slide);

  const language = $derived(resolveProjectLanguage(project));
  const theme = $derived(previewProjectSetting("theme") ?? project.theme);
  const previewBlackCodeBackground = $derived(
    previewProjectSetting("useBlackCodeBackground"),
  );

  const shiki = magicMoveShikiDisplay(() => ({ theme, language }));

  const s = $derived(project.settings);
  const fontSize = $derived(effective.settings.fontSize);
  const lineHeight = $derived(effective.settings.lineHeight);

  const bg = $derived(
    (previewBlackCodeBackground ?? s.useBlackCodeBackground)
      ? "#000000"
      : themeBackground(shiki.displayTheme),
  );
  const centerBlock = $derived(s.codeAlign === "center");

  const stagePad = $derived(isPresenting ? "p-16 md:p-24" : "p-8 md:p-12");

  const rawHighlights = $derived(slide?.highlights ?? []);
  const highlights = $derived(previewMergedHighlights(rawHighlights));

  const activeHighlight = $derived(
    activeHighlightIndex >= 0 && activeHighlightIndex < highlights.length
      ? highlights[activeHighlightIndex]
      : null,
  );

  const previewFontSize = $derived(isPresenting ? fontSize * 1.15 : fontSize);
</script>

{#if !slide}
  <div class="flex h-full w-full items-center justify-center text-muted-foreground">
    No slides
  </div>
{:else if !shiki.displayHighlighter}
  <PreviewFallback
    isMerustmarFail={language === "merustmar" && shiki.shikiLoadFailed}
    theme={shiki.displayTheme}
    {code}
    fontSize={previewFontSize}
    {lineHeight}
    {stagePad}
    {centerBlock}
    {bg}
    bind:ref={containerEl}
  />
{:else}
  <PreviewStage bind:ref={containerEl} {bg} {stagePad} {centerBlock}>
    <MagicMoveBlock
      bind:ref={codeContainerEl}
      {centerBlock}
      {lineHeight}
      fontSize={previewFontSize}
      theme={shiki.displayTheme}
      language={shiki.displayLanguage}
      highlighter={shiki.displayHighlighter}
      {code}
      transition={effective.settings.transitionDuration}
      stagger={effective.settings.stagger}
      showLineNumbers={s.showLineNumbers}
    />
    <HighlightLayer
      container={() => containerEl}
      codeContainer={() => codeContainerEl}
      code={() => code}
      highlight={() => activeHighlight}
      highlighter={() => shiki.displayHighlighter}
      theme={() => shiki.displayTheme}
      language={() => shiki.displayLanguage}
      fontSize={() => previewFontSize}
      lineHeight={() => lineHeight}
      onExitComplete={onHighlightExitComplete}
    />
  </PreviewStage>
{/if}
