// src/components/ui/chip.tsx
import { cn } from "@/lib/utils";

interface ChipProps extends React.HTMLAttributes<HTMLSpanElement> {}

export function Chip({ className, ...props }: ChipProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md bg-black/60 px-2.5 py-1 text-xs text-white/80 backdrop-blur",
        className,
      )}
      {...props}
    />
  );
}

// src/shared/ui/Chip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { cn } from "$lib/lib/utils";

  let {
    class: className,
    children,
    ...rest
  }: HTMLAttributes<HTMLSpanElement> & { class?: string; children?: Snippet } = $props();
</script>

<span
  class={cn(
    "inline-flex items-center gap-1.5 rounded-md bg-black/60 px-2.5 py-1 text-xs text-white/80 backdrop-blur",
    className,
  )}
  {...rest}
>
  {@render children?.()}
</span>
