// src/components/ui/settings-section.tsx
import { cn } from "@/lib/utils";

interface SettingsSectionProps {
  title: string;
  description?: string;
  children: React.ReactNode;
  className?: string;
  /** Adds a top border + padding to separate this section from the one above */
  borderTop?: boolean;
}

export function SettingsSection({
  title,
  description,
  children,
  className,
  borderTop = false,
}: SettingsSectionProps) {
  return (
    <section
      className={cn(
        "space-y-3",
        borderTop && "border-t pt-4",
        className,
      )}
    >
      <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        {title}
      </h3>
      {description && (
        <p className="text-[11px] text-muted-foreground">{description}</p>
      )}
      {children}
    </section>
  );
}

// src/shared/ui/SettingsSection.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "$lib/lib/utils";

  let {
    title,
    description,
    borderTop = false,
    class: className,
    children,
  }: {
    title: string;
    description?: string;
    class?: string;
    /** Adds a top border + padding to separate this section from the one above */
    borderTop?: boolean;
    children?: Snippet;
  } = $props();
</script>

<section class={cn("space-y-3", borderTop && "border-t pt-4", className)}>
  <h3
    class="text-xs font-semibold tracking-wide text-muted-foreground uppercase"
  >
    {title}
  </h3>
  {#if description}
    <p class="text-[11px] text-muted-foreground">{description}</p>
  {/if}
  {@render children?.()}
</section>
