// src/components/dashboard/DashboardStates.tsx
import { Plus, Upload, FolderOpen } from "lucide-react";
import { Button } from "../ui/button";
import { EmptyState } from "../ui/empty-state";
import { AsyncState } from "../states/async-state";

interface DashboardStatesProps {
  isLoading: boolean;
  isError: boolean;
  error: Error | null;
  projectCount: number;
  onCreate: () => void;
  onImport: () => void;
  /** Hide the default empty prompt while the custom create form is open. */
  showEmptyState?: boolean;
  children: React.ReactNode;
}

export function DashboardStates({
  isLoading,
  isError,
  error,
  projectCount,
  onCreate,
  onImport,
  showEmptyState = true,
  children,
}: DashboardStatesProps) {
  if (isLoading || isError) {
    return (
      <AsyncState
        isLoading={isLoading}
        isError={isError}
        error={error}
        loadingLabel="Loading presentations…"
      />
    );
  }

  if (projectCount === 0 && showEmptyState) {
    return (
      <EmptyState
        icon={FolderOpen}
        title="No presentations yet"
        description="Create your first presentation, or import an existing one."
      >
        <Button onClick={onCreate} className="gap-2">
          <Plus className="h-4 w-4" />Create Presentation
        </Button>
        <Button variant="outline" onClick={onImport} className="gap-2">
          <Upload className="h-4 w-4" />Import
        </Button>
      </EmptyState>
    );
  }

  return <>{children}</>;
}

// src/features/dashboard/DashboardStates.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { Plus, Upload, FolderOpen } from "@lucide/svelte";
  import Button from "$lib/ui/Button.svelte";
  import EmptyState from "$lib/ui/EmptyState.svelte";
  import AsyncState from "$lib/components/AsyncState.svelte";

  let {
    isLoading,
    isError,
    error,
    projectCount,
    onCreate,
    onImport,
    showEmptyState = true,
    children,
  }: {
    isLoading: boolean;
    isError: boolean;
    error: Error | null;
    projectCount: number;
    onCreate: () => void;
    onImport: () => void;
    /** Hide the default empty prompt while the custom create form is open. */
    showEmptyState?: boolean;
    children?: Snippet;
  } = $props();
</script>

{#if isLoading || isError}
  <AsyncState {isLoading} {isError} {error} loadingLabel="Loading presentations…" />
{:else if projectCount === 0 && showEmptyState}
  <EmptyState
    icon={FolderOpen}
    title="No presentations yet"
    description="Create your first presentation, or import an existing one."
  >
    <Button onclick={onCreate} class="gap-2">
      <Plus class="h-4 w-4" />Create Presentation
    </Button>
    <Button variant="outline" onclick={onImport} class="gap-2">
      <Upload class="h-4 w-4" />Import
    </Button>
  </EmptyState>
{:else}
  {@render children?.()}
{/if}
