// src/components/slides/SlideCardHeader.tsx
import { DragHandle } from "../ui/drag-handle";
import { InlineEditableText } from "../ui/inline-editable-text";

interface SlideCardHeaderProps {
  isRenaming: boolean;
  renameValue: string;
  title: string;
  dragHandleProps?: React.HTMLAttributes<HTMLButtonElement>;
  onRenameValueChange?: (v: string) => void;
  onCommitRename?: () => void;
  onCancelRename?: () => void;
  onRename?: (id: string, current: string) => void;
  slideId: string;
}

export function SlideCardHeader({
  isRenaming,
  renameValue,
  title,
  dragHandleProps,
  onRenameValueChange,
  onCommitRename,
  onCancelRename,
  onRename,
  slideId,
}: SlideCardHeaderProps) {
  return (
    <div className="flex min-w-0 items-center justify-between gap-1">
      <div className="flex min-w-0 items-center gap-1">
        <DragHandle
          {...dragHandleProps}
          onClick={(e) => e.stopPropagation()}
          aria-label="Drag to reorder slide"
        />
        {isRenaming ? (
          <InlineEditableText
            value={renameValue}
            onChange={(v) => onRenameValueChange?.(v)}
            onCommit={() => onCommitRename?.()}
            onCancel={() => onCancelRename?.()}
            className="h-5 min-w-0 flex-1 rounded px-1 text-xs font-medium"
          />
        ) : (
          <span
            className="truncate text-xs font-medium"
            title={`${title} — double-click or right-click to rename`}
            onDoubleClick={(e) => {
              if (!onRename) return;
              e.stopPropagation();
              onRename(slideId, title);
            }}
          >
            {title}
          </span>
        )}
      </div>
    </div>
  );
}

// src/features/slides/SlideCardHeader.svelte
<script lang="ts">
  import DragHandle from "$lib/ui/DragHandle.svelte";
  import InlineEditableText from "$lib/ui/InlineEditableText.svelte";

  let {
    isRenaming,
    renameValue,
    title,
    onRenameValueChange,
    onCommitRename,
    onCancelRename,
    onRename,
    slideId,
  }: {
    isRenaming: boolean;
    renameValue: string;
    title: string;
    onRenameValueChange?: (v: string) => void;
    onCommitRename?: () => void;
    onCancelRename?: () => void;
    onRename?: (id: string, current: string) => void;
    slideId: string;
  } = $props();
</script>

<div class="flex min-w-0 items-center justify-between gap-1">
  <div class="flex min-w-0 items-center gap-1">
    <DragHandle onclick={(e) => e.stopPropagation()} aria-label="Drag to reorder slide" />
    {#if isRenaming}
      <InlineEditableText
        value={renameValue}
        onChange={(v) => onRenameValueChange?.(v)}
        onCommit={() => onCommitRename?.()}
        onCancel={() => onCancelRename?.()}
        class="h-5 min-w-0 flex-1 rounded px-1 text-xs font-medium"
      />
    {:else}
      <!-- Rename affordance: same action as the context-menu rename.
           Enter/Space mirrors the double-click for keyboard users. -->
      <span
        class="truncate text-xs font-medium"
        title="{title} — double-click or right-click to rename"
        role="button"
        tabindex="0"
        onkeydown={(e) => {
          if (!onRename || (e.key !== "Enter" && e.key !== " ")) return;
          e.preventDefault();
          e.stopPropagation();
          onRename(slideId, title);
        }}
        ondblclick={(e) => {
          if (!onRename) return;
          e.stopPropagation();
          onRename(slideId, title);
        }}
      >
        {title}
      </span>
    {/if}
  </div>
</div>
