// src/components/highlights/HighlightEraserSegments.tsx
import { motion } from "framer-motion";
import type { HighlightMeasurement } from "@/lib/highlight-utils";
import type { HighlightPlan } from "@/lib/highlight-tokens";
import { EASE_DIM } from "./easings";



interface HighlightEraserSegmentsProps {
  highlightId: string;
  measurement: HighlightMeasurement;
  plan: HighlightPlan;
  dimDuration: number;
}

export function HighlightEraserSegments({
  highlightId,
  measurement,
  plan,
  dimDuration,
}: HighlightEraserSegmentsProps) {
  return (
    <>
      {measurement.segments.map((seg) => (
        <motion.div
          key={`${highlightId}-eraser-${seg.line.lineIndex}`}
          className="pointer-events-none absolute z-20"
          style={{
            left: seg.rect.x,
            top: seg.rect.y,
            width: seg.rect.width,
            height: seg.rect.height,
            backgroundColor: plan.eraserColor,
            willChange: "opacity",
            transform: "translateZ(0)",
          }}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: dimDuration, ease: EASE_DIM }}
        />
      ))}
    </>
  );
}

// src/features/highlights/HighlightEraserSegments.svelte
<script lang="ts">
  /**
   * Per-line "eraser" boxes painted in the card background color over the
   * old code so only the highlighted selection remains visible.
   *
   * Keyed per (highlightId, line) — on step change the old boxes fade out
   * while the new ones fade in, matching the AnimatePresence crossfade.
   */
  import { fade } from "svelte/transition";
  import type { HighlightMeasurement } from "@/features/highlights/highlight-utils";
  import type { HighlightPlan } from "@/features/highlights/highlight-tokens";
  import { EASE_DIM } from "$lib/lib/easings";

  let {
    highlightId,
    measurement,
    plan,
    dimMs,
    onOutroStart,
    onOutroEnd,
  }: {
    highlightId: string;
    measurement: HighlightMeasurement;
    plan: HighlightPlan;
    dimMs: number;
    onOutroStart?: () => void;
    onOutroEnd?: () => void;
  } = $props();
</script>

{#each measurement.segments as seg (`${highlightId}-eraser-${seg.line.lineIndex}`)}
  <div
    class="pointer-events-none absolute z-20"
    style="left: {seg.rect.x}px; top: {seg.rect.y}px; width: {seg.rect.width}px; height: {seg.rect.height}px; background-color: {plan.eraserColor}; will-change: opacity; transform: translateZ(0);"
    transition:fade|global={{ duration: dimMs, easing: EASE_DIM }}
    onoutrostart={onOutroStart}
    onoutroend={onOutroEnd}
  ></div>
{/each}
