// src/components/CommandPalette.svelte
<script lang="ts">
  /**
   * Cmd/Ctrl+K command palette for quick actions.
   */
  import { Command } from "cmdk-sv";
  import type { Snippet } from "svelte";
  import {
    Home,
    MonitorPlay,
    Settings,
    Download,
    Focus,
    Moon,
    Sun,
    Plus,
    Keyboard,
  } from "lucide-svelte";
  import { push } from "svelte-spa-router";
  import {
    ui,
    setIsCommandOpen,
    setIsPresenting,
    setIsSettingsOpen,
    setIsShortcutsOpen,
    toggleZenMode,
    toggleTheme,
  } from "@/store/ui-state.svelte";
  import { THEME_OPTIONS, type ThemeName } from "@/types";
  import { cn } from "@/lib/utils";
  import Kbd from "./ui/Kbd.svelte";
  import CommandDialog from "./ui/CommandDialog.svelte";
  import { modKeyLabel } from "@/lib/platform";
  import { isModKey } from "@/lib/keyboard";

  let {
    projectId,
    onExport,
    onAddSlide,
    onTheme,
  }: {
    projectId?: string;
    onExport?: () => void;
    onAddSlide?: () => void;
    onTheme?: (theme: ThemeName) => void;
  } = $props();

  let search = $state("");
  const mod = modKeyLabel();

  $effect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (isModKey(e) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setIsCommandOpen(!ui.isCommandOpen);
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  });

  $effect(() => {
    if (!ui.isCommandOpen) search = "";
  });

  function run(fn: () => void) {
    fn();
    setIsCommandOpen(false);
  }

  const itemClass = cn(
    "flex cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-sm text-foreground",
    "data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground",
  );
</script>

{#snippet item(icon: Snippet, label: string, onSelect: () => void)}
  <Command.Item {onSelect} class={itemClass}>
    {@render icon()}
    <span>{label}</span>
  </Command.Item>
{/snippet}

<CommandDialog
  open={ui.isCommandOpen}
  onClose={() => setIsCommandOpen(false)}
  label="Command Menu"
  placeholder="Type a command or search…"
  bind:search={search}
  class="w-full max-w-lg"
>
  <Command.Group heading="Navigation" class="text-xs text-muted-foreground">
    {@render item(homeIcon, "Go to Dashboard", () => run(() => void push("/")))}
    {#if projectId}
      {@render item(presentIcon, "Start Presentation", () => run(() => setIsPresenting(true)))}
      {@render item(settingsIcon, "Open Settings", () => run(() => setIsSettingsOpen(true)))}
      {@render item(focusIcon, "Toggle focus mode", () => run(() => toggleZenMode()))}
      {@render item(plusIcon, "Add Slide", () => run(() => onAddSlide?.()))}
      {@render item(downloadIcon, "Export presentation", () => run(() => onExport?.()))}
    {/if}
    {@render item(themeIcon, ui.isDarkUi ? "Switch to light mode" : "Switch to dark mode", () =>
      run(() => toggleTheme()),
    )}
    {@render item(keyboardIcon, "Keyboard shortcuts", () => run(() => setIsShortcutsOpen(true)))}
  </Command.Group>

  {#if projectId && onTheme}
    <Command.Group heading="Themes" class="mt-2 text-xs text-muted-foreground">
      {#each THEME_OPTIONS as t (t.value)}
        {@render item(themeDot, t.label, () => run(() => onTheme(t.value)))}
      {/each}
    </Command.Group>
  {/if}

  {#snippet footer()}
    <div class="border-t px-3 py-2 text-[10px] text-muted-foreground">
      <Kbd>Esc</Kbd> to close · <Kbd>{mod}K</Kbd> toggle
    </div>
  {/snippet}
</CommandDialog>

{#snippet homeIcon()}<Home class="h-4 w-4" />{/snippet}
{#snippet presentIcon()}<MonitorPlay class="h-4 w-4" />{/snippet}
{#snippet settingsIcon()}<Settings class="h-4 w-4" />{/snippet}
{#snippet focusIcon()}<Focus class="h-4 w-4" />{/snippet}
{#snippet plusIcon()}<Plus class="h-4 w-4" />{/snippet}
{#snippet downloadIcon()}<Download class="h-4 w-4" />{/snippet}
{#snippet keyboardIcon()}<Keyboard class="h-4 w-4" />{/snippet}
{#snippet themeIcon()}
  {#if ui.isDarkUi}<Sun class="h-4 w-4" />{:else}<Moon class="h-4 w-4" />{/if}
{/snippet}
{#snippet themeDot()}<span class="h-2 w-2 rounded-full bg-primary"></span>{/snippet}

// src/components/CommandPalette.tsx
/**
 * Cmd/Ctrl+K command palette for quick actions.
 */
import { useEffect, useState } from "react";
import { Command } from "cmdk";
import {
  Home,
  MonitorPlay,
  Settings,
  Download,
  Focus,
  Moon,
  Sun,
  Plus,
  Keyboard,
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useUiStore } from "@/store/useUiStore";
import { THEME_OPTIONS, type ThemeName } from "@/types";
import { cn } from "@/lib/utils";
import { Kbd } from "./ui/kbd";
import { CommandDialog } from "./ui/command-dialog";
import { modKeyLabel } from "@/lib/platform";
import { isModKey } from "@/lib/keyboard";

interface CommandPaletteProps {
  projectId?: string;
  onExport?: () => void;
  onAddSlide?: () => void;
  onTheme?: (theme: ThemeName) => void;
}

export function CommandPalette({
  projectId,
  onExport,
  onAddSlide,
  onTheme,
}: CommandPaletteProps) {
  const navigate = useNavigate();
  const isCommandOpen = useUiStore((s) => s.isCommandOpen);
  const setIsCommandOpen = useUiStore((s) => s.setIsCommandOpen);
  const setIsPresenting = useUiStore((s) => s.setIsPresenting);
  const setIsSettingsOpen = useUiStore((s) => s.setIsSettingsOpen);
  const setIsShortcutsOpen = useUiStore((s) => s.setIsShortcutsOpen);
  const toggleZenMode = useUiStore((s) => s.toggleZenMode);
  const isDarkUi = useUiStore((s) => s.isDarkUi);
  const toggleTheme = useUiStore((s) => s.toggleTheme);
  const [search, setSearch] = useState("");
  const mod = modKeyLabel();

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (isModKey(e) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setIsCommandOpen(!isCommandOpen);
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [isCommandOpen, setIsCommandOpen]);

  useEffect(() => {
    if (!isCommandOpen) setSearch("");
  }, [isCommandOpen]);

  const run = (fn: () => void) => {
    fn();
    setIsCommandOpen(false);
  };

  return (
    <CommandDialog
      open={isCommandOpen}
      onClose={() => setIsCommandOpen(false)}
      label="Command Menu"
      placeholder="Type a command or search…"
      search={search}
      onSearchChange={setSearch}
      className="w-full max-w-lg"
      footer={
        <div className="border-t px-3 py-2 text-[10px] text-muted-foreground">
          <Kbd>Esc</Kbd> to close · <Kbd>{mod}K</Kbd> toggle
        </div>
      }
    >
      <Command.Group heading="Navigation" className="text-xs text-muted-foreground">
        <Item
          icon={<Home className="h-4 w-4" />}
          label="Go to Dashboard"
          onSelect={() => run(() => navigate("/"))}
        />
        {projectId && (
          <>
            <Item
              icon={<MonitorPlay className="h-4 w-4" />}
              label="Start Presentation"
              onSelect={() => run(() => setIsPresenting(true))}
            />
            <Item
              icon={<Settings className="h-4 w-4" />}
              label="Open Settings"
              onSelect={() => run(() => setIsSettingsOpen(true))}
            />
            <Item
              icon={<Focus className="h-4 w-4" />}
              label="Toggle focus mode"
              onSelect={() => run(() => toggleZenMode())}
            />
            <Item
              icon={<Plus className="h-4 w-4" />}
              label="Add Slide"
              onSelect={() => run(() => onAddSlide?.())}
            />
            <Item
              icon={<Download className="h-4 w-4" />}
              label="Export presentation"
              onSelect={() => run(() => onExport?.())}
            />
          </>
        )}
        <Item
          icon={isDarkUi ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
          label={isDarkUi ? "Switch to light mode" : "Switch to dark mode"}
          onSelect={() => run(() => toggleTheme())}
        />
        <Item
          icon={<Keyboard className="h-4 w-4" />}
          label="Keyboard shortcuts"
          onSelect={() => run(() => setIsShortcutsOpen(true))}
        />
      </Command.Group>

      {projectId && onTheme && (
        <Command.Group heading="Themes" className="mt-2 text-xs text-muted-foreground">
          {THEME_OPTIONS.map((t) => (
            <Item
              key={t.value}
              icon={<span className="h-2 w-2 rounded-full bg-primary" />}
              label={t.label}
              onSelect={() => run(() => onTheme(t.value))}
            />
          ))}
        </Command.Group>
      )}
    </CommandDialog>
  );
}

function Item({
  icon,
  label,
  onSelect,
}: {
  icon: React.ReactNode;
  label: string;
  onSelect: () => void;
}) {
  return (
    <Command.Item
      onSelect={onSelect}
      className={cn(
        "flex cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-sm text-foreground",
        "data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground",
      )}
    >
      {icon}
      <span>{label}</span>
    </Command.Item>
  );
}
