// src/components/TitleBar.svelte
<script lang="ts">
  /**
   * In-app toolbar strip. Window chrome (traffic lights / caption buttons)
   * is handled by the OS via native decorations — no custom window controls.
   */
  import type { Snippet } from "svelte";
  import { cn } from "@/lib/utils";

  let {
    title,
    class: className,
    leading,
    trailing,
    borderless,
  }: {
    title?: string;
    class?: string;
    leading?: Snippet;
    trailing?: Snippet;
    /** When true, omit the bottom border (merged into a single bar). */
    borderless?: boolean;
  } = $props();
</script>

<div
  class={cn(
    "flex h-11 shrink-0 items-center justify-between gap-3 bg-card/70 px-3 backdrop-blur-md",
    !borderless && "border-b border-border/60",
    className,
  )}
>
  <div class="flex min-w-0 items-center gap-2">
    {@render leading?.()}
    {#if title}
      <span class="truncate text-sm font-medium text-foreground/90">{title}</span>
    {/if}
  </div>
  <div class="flex shrink-0 items-center gap-1">{@render trailing?.()}</div>
</div>

// src/components/TitleBar.tsx
/**
 * In-app toolbar strip. Window chrome (traffic lights / caption buttons)
 * is handled by the OS via native decorations — no custom window controls.
 */
import { cn } from "@/lib/utils";

interface TitleBarProps {
  title?: string;
  className?: string;
  leading?: React.ReactNode;
  trailing?: React.ReactNode;
  /** When true, omit the bottom border (merged into a single bar). */
  borderless?: boolean;
}

export function TitleBar({
  title,
  className,
  leading,
  trailing,
  borderless,
}: TitleBarProps) {
  return (
    <div
      className={cn(
        "flex h-11 shrink-0 items-center justify-between gap-3 bg-card/70 px-3 backdrop-blur-md",
        !borderless && "border-b border-border/60",
        className,
      )}
    >
      <div className="flex min-w-0 items-center gap-2">
        {leading}
        {title && (
          <span className="truncate text-sm font-medium text-foreground/90">{title}</span>
        )}
      </div>
      <div className="flex shrink-0 items-center gap-1">{trailing}</div>
    </div>
  );
}
