// src/features/slides/SlideSearchDialog.svelte
<script lang="ts" module>
  export type SearchScope = "slides" | "code";
</script>

<script lang="ts">
  /** Centered find control that leaves the workspace visible behind it. */
  import { Search } from "@lucide/svelte";
  import { fade } from "svelte/transition";
  import { Z_INDEX } from "$lib/ui/Overlay.svelte";
  import { modKeyLabel } from "$lib/lib/platform";
  import { rise } from "$lib/ui/transitions/rise";
  import { EASE_DIM } from "$lib/lib/easings";

  let {
    open,
    query,
    scope,
    onQueryChange,
    onScopeChange,
    onSubmitCodeSearch,
    onClose,
  }: {
    open: boolean;
    query: string;
    scope: SearchScope;
    onQueryChange: (value: string) => void;
    onScopeChange: (scope: SearchScope) => void;
    onSubmitCodeSearch: () => void;
    onClose: () => void;
  } = $props();

  let inputEl = $state<HTMLInputElement | null>(null);


  $effect(() => {
    if (!open) return;
    const raf = requestAnimationFrame(() => inputEl?.focus());
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
      if (event.key === "Enter" && scope === "code") onSubmitCodeSearch();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("keydown", onKeyDown);
    };
  });
</script>

{#if open}
  <div
    class="fixed inset-0 flex items-center justify-center p-4"
    style="z-index: {Z_INDEX.command};"
    transition:fade={{ duration: 150, easing: EASE_DIM }}
  >
    <button type="button" class="absolute inset-0 cursor-default" aria-label="Close search" onclick={onClose}></button>
    <div
      class="relative w-full max-w-lg overflow-hidden rounded-xl border bg-card shadow-2xl"
      transition:rise={{ duration: 150, dy: 8, from: 0.98 }}
    >
      <div class="flex items-center gap-2 border-b px-4 py-3">
        <Search class="h-4 w-4 text-muted-foreground" />
        <input
          bind:this={inputEl}
          value={query}
          oninput={(event) => onQueryChange(event.currentTarget.value)}
          placeholder={scope === "slides"
            ? "Find slides by name or code…"
            : "Find in the current editor…"}
          class="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        />
        <span class="text-[10px] text-muted-foreground">{modKeyLabel()}F</span>
      </div>
      <div class="flex items-center gap-2 px-4 py-3 text-xs">
        <span class="mr-1 text-muted-foreground">Search</span>
        <label class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted">
          <input
            type="radio"
            name="search-scope"
            checked={scope === "slides"}
            onchange={() => onScopeChange("slides")}
          />
          Slides
        </label>
        <label class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted">
          <input
            type="radio"
            name="search-scope"
            checked={scope === "code"}
            onchange={() => onScopeChange("code")}
          />
          Code editor
        </label>
        <span class="ml-auto text-[10px] text-muted-foreground">
          {scope === "code" ? "Enter to find" : "Results update below"}
        </span>
      </div>
    </div>
  </div>
{/if}

// src/components/slides/SlideSearchDialog.tsx
import { useEffect, useRef } from "react";
import { Search } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Z_INDEX } from "../ui/overlay";
import { modKeyLabel } from "@/lib/platform";

export type SearchScope = "slides" | "code";

interface SlideSearchDialogProps {
  open: boolean;
  query: string;
  scope: SearchScope;
  onQueryChange: (value: string) => void;
  onScopeChange: (scope: SearchScope) => void;
  onSubmitCodeSearch: () => void;
  onClose: () => void;
}

/** Centered find control that leaves the workspace visible behind it. */
export function SlideSearchDialog({
  open,
  query,
  scope,
  onQueryChange,
  onScopeChange,
  onSubmitCodeSearch,
  onClose,
}: SlideSearchDialogProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!open) return;
    requestAnimationFrame(() => inputRef.current?.focus());
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
      if (event.key === "Enter" && scope === "code") onSubmitCodeSearch();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [onClose, onSubmitCodeSearch, open, scope]);

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 flex items-center justify-center p-4"
          style={{ zIndex: Z_INDEX.command }}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <button
            type="button"
            className="absolute inset-0 cursor-default"
            aria-label="Close search"
            onClick={onClose}
          />
          <motion.div
            className="relative w-full max-w-lg overflow-hidden rounded-xl border bg-card shadow-2xl"
            initial={{ opacity: 0, y: 8, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 8, scale: 0.98 }}
            transition={{ duration: 0.15 }}
          >
            <div className="flex items-center gap-2 border-b px-4 py-3">
              <Search className="h-4 w-4 text-muted-foreground" />
              <input
                ref={inputRef}
                value={query}
                onChange={(event) => onQueryChange(event.target.value)}
                placeholder={scope === "slides" ? "Find slides by name or code…" : "Find in the current editor…"}
                className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
              />
              <span className="text-[10px] text-muted-foreground">{modKeyLabel()}F</span>
            </div>
            <div className="flex items-center gap-2 px-4 py-3 text-xs">
              <span className="mr-1 text-muted-foreground">Search</span>
              <label className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted">
                <input type="radio" name="search-scope" checked={scope === "slides"} onChange={() => onScopeChange("slides")} />
                Slides
              </label>
              <label className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted">
                <input type="radio" name="search-scope" checked={scope === "code"} onChange={() => onScopeChange("code")} />
                Code editor
              </label>
              <span className="ml-auto text-[10px] text-muted-foreground">
                {scope === "code" ? "Enter to find" : "Results update below"}
              </span>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
