// src/features/slides/SlideCardHoverPreview.svelte
<script lang="ts">
  /** Fixed-position hover preview, portaled to body (react-dom createPortal). */
  import CodeThumbnail from "$lib/ui/CodeThumbnail.svelte";
  import { Z_INDEX } from "$lib/ui/Overlay.svelte";
  import { portal } from "$lib/actions/portal";

  let {
    show,
    html,
    containerEl = $bindable(null),
    theme,
    left,
    top,
  }: {
    show: boolean;
    html: string | null | undefined;
    containerEl?: HTMLDivElement | null;
    theme: string;
    left: number;
    top: number;
  } = $props();
</script>

{#if show && html}
  <div use:portal>
    <CodeThumbnail
      bind:ref={containerEl}
      html={html ?? null}
      {theme}
      fontSize={8}
      class="pointer-events-none fixed h-[170px] w-[300px] rounded-lg border border-border bg-card p-2 shadow-2xl"
      style="left: {left}px; top: {top}px; z-index: {Z_INDEX.hoverPreview};"
    />
  </div>
{/if}

// src/components/slides/SlideCardHoverPreview.tsx
import { createPortal } from "react-dom";
import { CodeThumbnail } from "../ui/code-thumbnail";
import { Z_INDEX } from "../ui/overlay";

interface SlideCardHoverPreviewProps {
  show: boolean;
  html: string | null | undefined;
  containerRef: React.Ref<HTMLDivElement>;
  theme: string;
  left: number;
  top: number;
}

export function SlideCardHoverPreview({
  show,
  html,
  containerRef,
  theme,
  left,
  top,
}: SlideCardHoverPreviewProps) {
  if (!show || !html) return null;

  return createPortal(
    <CodeThumbnail
      containerRef={containerRef}
      html={html}
      theme={theme}
      fontSize={8}
      className="pointer-events-none fixed h-[170px] w-[300px] rounded-lg border border-border bg-card p-2 shadow-2xl"
      style={{ left, top, zIndex: Z_INDEX.hoverPreview }}
    />,
    document.body,
  );
}
