// src/components/editor/PresentOverlay.tsx
/**
 * PresentOverlay — fullscreen presentation stage.
 * Isolated from Editor god component. Only selects autoplay slice + props.
 * Enhancement: HighlightStepIndicator now clickable to jump to steps.
 * Enhancement: Presentation timer + progress bar for autoplay (TypeScript, not Rust — UI animation, no DB needed)
 */
import { memo } from "react";
import { SlidePreview } from "../SlidePreview";
import { HighlightStepIndicator } from "../HighlightStepIndicator";
import { ProgressBar } from "../ui/progress-bar";
import { AutoplayTimerChip } from "../presentation/AutoplayTimerChip";
import { PresentControls } from "../presentation/PresentControls";
import { usePresentationControls } from "@/store/ui-selectors";
import type { Project, Slide } from "@/types";
import { Z_INDEX } from "../ui/overlay";

interface PresentOverlayProps {
  project: Project;
  activeSlide?: Slide;
  activeHighlightIndex: number;
  onHighlightExitComplete: () => void;
  goNext: () => boolean;
  goPrev: () => boolean;
  goToHighlight: (index: number) => boolean;
  exitPresent: () => void;
}

export const PresentOverlay = memo(function PresentOverlay({
  project,
  activeSlide,
  activeHighlightIndex,
  onHighlightExitComplete,
  goNext,
  goPrev,
  goToHighlight,
  exitPresent,
}: PresentOverlayProps) {
  const { isAutoPlaying, toggleAutoPlaying, setIsAutoPlaying } =
    usePresentationControls();

  const duration = activeSlide?.duration ?? 3000;
  const resetKey = `${activeSlide?.id}-${duration}-${activeHighlightIndex}`;

  return (
    <div
      id="openslides-present-root"
      className="fixed inset-0 flex items-center justify-center bg-black"
      style={{ zIndex: Z_INDEX.presentation }}
    >
      {/* Slide duration progress bar — TypeScript timer, not Rust, for smooth 60fps animation */}
      {isAutoPlaying && (
        <ProgressBar
          duration={duration}
          resetKey={resetKey}
          className="absolute left-0 top-0 h-1 w-full bg-white/10"
          style={{ zIndex: Z_INDEX.presentationProgress }}
        />
      )}

      <div className="absolute right-4 top-4 flex items-center gap-2" style={{ zIndex: Z_INDEX.presentationControls }}>
        {isAutoPlaying && (
          <AutoplayTimerChip duration={duration} resetKey={resetKey} />
        )}
        <PresentControls
          isAutoPlaying={isAutoPlaying}
          onToggleAutoplay={toggleAutoPlaying}
          onExit={() => void exitPresent()}
        />
      </div>

      {/* Full-bleed stage — Click next, right-click back */}
      <div
        className="flex h-full w-full cursor-pointer items-center justify-center p-0 sm:p-4"
        onClick={() => {
          setIsAutoPlaying(false);
          goNext();
        }}
        onContextMenu={(e) => {
          e.preventDefault();
          setIsAutoPlaying(false);
          goPrev();
        }}
      >
        <div className="relative aspect-video h-full max-h-full w-full max-w-full">
          <SlidePreview
            project={project}
            isPresenting
            activeHighlightIndex={activeHighlightIndex}
            onHighlightExitComplete={onHighlightExitComplete}
          />
          {/* Bottom bar: timer (left) + highlight dots (center) — both clickable */}
          <div className="absolute inset-x-0 bottom-4 z-40 flex items-center justify-between px-4">
            <div className="flex-1" />
            <div className="pointer-events-none flex justify-center">
              <div className="pointer-events-auto">
                <HighlightStepIndicator
                  total={activeSlide?.highlights?.length ?? 0}
                  current={activeHighlightIndex}
                  onSelect={(idx) => {
                    setIsAutoPlaying(false);
                    goToHighlight(idx);
                  }}
                />
              </div>
            </div>
            <div className="flex-1" />
          </div>
        </div>
      </div>
    </div>
  );
});

// src/features/presentation/PresentOverlay.svelte
<script lang="ts">
  /**
   * PresentOverlay — fullscreen presentation stage.
   * HighlightStepIndicator is clickable to jump to steps.
   * Presentation timer + progress bar for autoplay (UI animation only).
   */
  import SlidePreview from "@/features/preview/SlidePreview.svelte";
  import HighlightStepIndicator from "@/features/highlights/HighlightStepIndicator.svelte";
  import ProgressBar from "$lib/ui/ProgressBar.svelte";
  import AutoplayTimerChip from "@/features/presentation/AutoplayTimerChip.svelte";
  import PresentControls from "@/features/presentation/PresentControls.svelte";
  import { ui, toggleAutoPlaying, setIsAutoPlaying } from "$lib/stores/ui-state.svelte";
  import type { Project, Slide } from "$lib/types";
  import { Z_INDEX } from "$lib/ui/Overlay.svelte";

  let {
    project,
    activeSlide,
    activeHighlightIndex,
    onHighlightExitComplete,
    goNext,
    goPrev,
    goToHighlight,
    exitPresent,
  }: {
    project: Project;
    activeSlide?: Slide;
    activeHighlightIndex: number;
    onHighlightExitComplete: () => void;
    goNext: () => boolean;
    goPrev: () => boolean;
    goToHighlight: (index: number) => boolean;
    exitPresent: () => void;
  } = $props();

  const isAutoPlaying = $derived(ui.isAutoPlaying);
  const duration = $derived(activeSlide?.duration ?? 3000);
  const resetKey = $derived(
    `${activeSlide?.id}-${duration}-${activeHighlightIndex}`,
  );
</script>

<div
  id="openslides-present-root"
  class="fixed inset-0 flex items-center justify-center bg-black"
  style="z-index: {Z_INDEX.presentation}"
>
  <!-- Slide duration progress bar — UI timer for smooth 60fps animation -->
  {#if isAutoPlaying}
    <ProgressBar
      {duration}
      {resetKey}
      class="absolute left-0 top-0 h-1 w-full bg-white/10"
      style="z-index: {Z_INDEX.presentationProgress}"
    />
  {/if}

  <div class="absolute right-4 top-4 flex items-center gap-2" style="z-index: {Z_INDEX.presentationControls}">
    {#if isAutoPlaying}
      <AutoplayTimerChip {duration} {resetKey} />
    {/if}
    <PresentControls
      {isAutoPlaying}
      onToggleAutoplay={toggleAutoPlaying}
      onExit={() => void exitPresent()}
    />
  </div>

  <!-- Full-bleed stage — Click next, right-click back -->
  <div
    class="flex h-full w-full cursor-pointer items-center justify-center p-0 sm:p-4"
    role="presentation"
    onclick={() => {
      setIsAutoPlaying(false);
      goNext();
    }}
    oncontextmenu={(e) => {
      e.preventDefault();
      setIsAutoPlaying(false);
      goPrev();
    }}
  >
    <div class="relative aspect-video h-full max-h-full w-full max-w-full">
      <SlidePreview
        {project}
        isPresenting
        {activeHighlightIndex}
        {onHighlightExitComplete}
      />
      {#if project.settings.showHighlightStepIndicator !== false}
        <div class="absolute inset-x-0 bottom-4 z-40 flex items-center justify-between px-4">
          <div class="flex-1"></div>
          <div class="pointer-events-none flex justify-center">
            <div
              class="pointer-events-auto"
              onclick={(event) => event.stopPropagation()}
              oncontextmenu={(event) => event.stopPropagation()}
              role="presentation"
            >
              <HighlightStepIndicator
                total={activeSlide?.highlights?.length ?? 0}
                current={activeHighlightIndex}
                onSelect={(idx) => {
                  setIsAutoPlaying(false);
                  goToHighlight(idx);
                }}
              />
            </div>
          </div>
          <div class="flex-1"></div>
        </div>
      {/if}
    </div>
  </div>
</div>
