// src/shared/ui/CodeThumbnail.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "$lib/lib/utils";
  import { themeBackground } from "$lib/types";

  let {
    html,
    fallback = null,
    theme,
    fontSize = 5.5,
    lineHeight = 1.35,
    class: className,
    codeClassName,
    ref = $bindable(null),
    style,
  }: {
    html: string | null;
    fallback?: Snippet | null;
    theme: string;
    fontSize?: number;
    lineHeight?: number;
    class?: string;
    codeClassName?: string;
    ref?: HTMLDivElement | null;
    style?: string;
  } = $props();
</script>

<div
  bind:this={ref}
  class={cn("relative w-full overflow-hidden", className)}
  style="background-color: {themeBackground(theme)};{style ?? ''}"
  aria-hidden="true"
>
  {#if html}
    <code
      class={cn("pointer-events-none block overflow-hidden font-mono", codeClassName)}
      style="font-size: {fontSize}px; line-height: {lineHeight}; white-space: pre;"
      >{@html html}</code
    >
  {:else if fallback}
    {@render fallback()}
  {/if}
</div>

// src/components/ui/code-thumbnail.tsx
import { cn } from "@/lib/utils";
import { themeBackground } from "@/types";

interface CodeThumbnailProps {
  html: string | null;
  fallback?: React.ReactNode;
  theme: string;
  fontSize?: number;
  lineHeight?: number;
  className?: string;
  codeClassName?: string;
  containerRef?: React.Ref<HTMLDivElement>;
  style?: React.CSSProperties;
}

export function CodeThumbnail({
  html,
  fallback = null,
  theme,
  fontSize = 5.5,
  lineHeight = 1.35,
  className,
  codeClassName,
  containerRef,
  style,
}: CodeThumbnailProps) {
  return (
    <div
      ref={containerRef}
      className={cn("relative w-full overflow-hidden", className)}
      style={{ backgroundColor: themeBackground(theme), ...style }}
      aria-hidden="true"
    >
      {html ? (
        <code
          className={cn(
            "pointer-events-none block overflow-hidden font-mono",
            codeClassName,
          )}
          style={{ fontSize: `${fontSize}px`, lineHeight, whiteSpace: "pre" }}
          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        fallback
      )}
    </div>
  );
}
