// src/components/ui/progress-bar.tsx
import { cn } from "@/lib/utils";

interface ProgressBarProps {
  duration: number;
  resetKey: string;
  className?: string;
  style?: React.CSSProperties;
}

export function ProgressBar({
  duration,
  resetKey,
  className,
  style,
}: ProgressBarProps) {
  return (
    <div className={cn("overflow-hidden", className)} style={style}>
      <div
        key={resetKey}
        className="openslides-progress-anim h-full w-full origin-left bg-primary"
        style={{
          animation: `openslides-present-progress ${duration}ms linear forwards`,
        }}
      />
    </div>
  );
}

// src/components/ui/ProgressBar.svelte
<script lang="ts">
  import { cn } from "@/lib/utils";

  let {
    duration,
    resetKey,
    class: className,
    style,
  }: {
    duration: number;
    resetKey: string;
    class?: string;
    style?: string;
  } = $props();
</script>

<div class={cn("overflow-hidden", className)} {style}>
  {#key resetKey}
    <div
      class="openslides-progress-anim h-full w-full origin-left bg-primary"
      style="animation: openslides-present-progress {duration}ms linear forwards;"
    ></div>
  {/key}
</div>
