// src/shared/ui/Slider.svelte
<script lang="ts">
  import { Slider } from "bits-ui";
  import { cn } from "$lib/lib/utils";

  let {
    value = $bindable([50]),
    min = 0,
    max = 100,
    step = 1,
    disabled = false,
    onValueChange,
    onValueCommit,
    class: className,
    ref = $bindable(null),
    ...rest
  }: {
    value?: number[];
    min?: number;
    max?: number;
    step?: number;
    disabled?: boolean;
    onValueChange?: (value: number[]) => void;
    onValueCommit?: (value: number[]) => void;
    class?: string;
    ref?: HTMLSpanElement | null;
  } = $props();
</script>

<Slider.Root
  bind:ref
  type="multiple"
  bind:value
  {min}
  {max}
  {step}
  {disabled}
  {onValueChange}
  {onValueCommit}
  class={cn(
    "relative flex w-full touch-none items-center select-none",
    disabled && "cursor-not-allowed opacity-50",
    className,
  )}
  {...rest}
>
  <!-- bits-ui v2: no Track subcomponent — the track is a plain span inside
       the Root's children snippet, and Thumb requires its `index`. -->
  {#snippet children({ thumbs })}
    <span
      class="relative h-1.5 w-full grow overflow-hidden rounded-full bg-primary/20"
    >
      <Slider.Range class="absolute h-full bg-primary" />
    </span>
    {#each thumbs as thumb (thumb)}
      <Slider.Thumb
        index={thumb}
        class="block h-4 w-4 rounded-full border border-primary/50 bg-background shadow transition-colors focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
      />
    {/each}
  {/snippet}
</Slider.Root>

// src/components/ui/slider.tsx
import * as React from "react";
import * as SliderPrimitive from "@radix-ui/react-slider";
import { cn } from "@/lib/utils";

export const Slider = React.forwardRef<
  React.ElementRef<typeof SliderPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root>
>(({ className, disabled, ...props }, ref) => (
  <SliderPrimitive.Root
    ref={ref}
    disabled={disabled}
    className={cn(
      "relative flex w-full touch-none select-none items-center",
      disabled && "cursor-not-allowed opacity-50",
      className,
    )}
    {...props}
  >
    <SliderPrimitive.Track className="relative h-1.5 w-full grow overflow-hidden rounded-full bg-primary/20">
      <SliderPrimitive.Range className="absolute h-full bg-primary" />
    </SliderPrimitive.Track>
    <SliderPrimitive.Thumb className="block h-4 w-4 rounded-full border border-primary/50 bg-background shadow transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50" />
  </SliderPrimitive.Root>
));
Slider.displayName = SliderPrimitive.Root.displayName;
